# Generated by Django 5.2.14 on 2026-05-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "pk_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("version", models.CharField(max_length=16)),
                ("book", models.CharField(max_length=8)),
                ("chapter", models.IntegerField()),
                ("verse", models.IntegerField()),
                ("text", models.TextField()),
            ],
            options={
                "managed": False,
            },
        ),
    ]
