# Generated by Django 5.2.14 on 2026-05-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcordanceEntry",
            fields=[
                (
                    "concord_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("original_word", models.TextField()),
                ("transliteration", models.TextField()),
                ("part_of_speech", models.TextField()),
                ("english_translations", models.JSONField(default=list)),
                ("outline_definitions", models.JSONField(default=list)),
                ("strongs_definition", models.JSONField(default=list)),
            ],
            options={
                "verbose_name_plural": "concordance entries",
            },
        ),
    ]
