# Generated by Django 5.2.14 on 2026-05-21 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0002_concordanceentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcordanceVerseMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=16)),
                ("book", models.CharField(max_length=8)),
                ("chapter", models.IntegerField()),
                ("verse", models.IntegerField()),
                (
                    "concord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verse_mappings",
                        to="bible.concordanceentry",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["version", "book", "chapter", "verse"],
                        name="bible_conco_version_7affdf_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("concord", "version", "book", "chapter", "verse"),
                        name="unique_concord_per_verse",
                    )
                ],
            },
        ),
    ]
