# Generated by Django 5.2.14 on 2026-05-21 21:02

from django.db import migrations, models

# (book_code, [author_names], date, is_bc) — applies to the whole book (chapter NULL).
# Chapter-specific rows below override the whole-book row for that chapter.
# Sources:
#   https://www.gotquestions.org/Bible-authors.html (whole-book attribution)
#   https://overviewbible.com/who-wrote-psalms-besides-david/ (per-chapter Psalms)
# Date ranges in the sources are reduced to their midpoint.
_WHOLE_BOOK_AUTHORSHIPS = (
    ("gen", ["Moses"], 1400, True),
    ("exo", ["Moses"], 1400, True),
    ("lev", ["Moses"], 1400, True),
    ("num", ["Moses"], 1400, True),
    ("deu", ["Moses"], 1400, True),
    ("jos", ["Joshua"], 1350, True),
    ("jdg", ["Samuel", "Nathan", "Gad"], 950, True),
    ("rth", ["Samuel", "Nathan", "Gad"], 950, True),
    ("1sa", ["Samuel", "Nathan", "Gad"], 950, True),
    ("2sa", ["Samuel", "Nathan", "Gad"], 950, True),
    ("1ki", ["Jeremiah"], 600, True),
    ("2ki", ["Jeremiah"], 600, True),
    ("1ch", ["Ezra"], 450, True),
    ("2ch", ["Ezra"], 450, True),
    ("ezr", ["Ezra"], 450, True),
    ("neh", ["Ezra"], 450, True),
    ("est", ["Mordecai"], 400, True),
    ("job", ["Moses"], 1400, True),
    # Psalms is covered entirely by per-chapter rows below — no whole-book
    # row. Orphan psalms (no explicit attribution) are not author-searchable.
    ("pro", ["Solomon"], 900, True),
    ("ecc", ["Solomon"], 900, True),
    ("sng", ["Solomon"], 900, True),
    ("isa", ["Isaiah"], 700, True),
    ("jer", ["Jeremiah"], 600, True),
    ("lam", ["Jeremiah"], 600, True),
    ("eze", ["Ezekiel"], 550, True),
    ("dan", ["Daniel"], 550, True),
    ("hos", ["Hosea"], 750, True),
    ("joe", ["Joel"], 850, True),
    ("amo", ["Amos"], 750, True),
    ("oba", ["Obadiah"], 600, True),
    ("jon", ["Jonah"], 700, True),
    ("mic", ["Micah"], 700, True),
    ("nah", ["Nahum"], 650, True),
    ("hab", ["Habakkuk"], 600, True),
    ("zep", ["Zephaniah"], 650, True),
    ("hag", ["Haggai"], 520, True),
    ("zec", ["Zechariah"], 500, True),
    ("mal", ["Malachi"], 430, True),
    ("mat", ["Matthew"], 55, False),
    ("mar", ["John Mark"], 50, False),
    ("luk", ["Luke"], 60, False),
    ("jhn", ["John"], 90, False),
    ("act", ["Luke"], 65, False),
    ("rom", ["Paul"], 60, False),
    ("1co", ["Paul"], 60, False),
    ("2co", ["Paul"], 60, False),
    ("gal", ["Paul"], 60, False),
    ("eph", ["Paul"], 60, False),
    ("phl", ["Paul"], 60, False),
    ("col", ["Paul"], 60, False),
    ("1th", ["Paul"], 60, False),
    ("2th", ["Paul"], 60, False),
    ("1ti", ["Paul"], 60, False),
    ("2ti", ["Paul"], 60, False),
    ("tit", ["Paul"], 60, False),
    ("phm", ["Paul"], 60, False),
    ("heb", ["Unknown", "Paul", "Luke", "Barnabas", "Apollos"], 65, False),
    ("jas", ["James"], 45, False),
    ("1pe", ["Peter"], 60, False),
    ("2pe", ["Peter"], 60, False),
    ("1jo", ["John"], 90, False),
    ("2jo", ["John"], 90, False),
    ("3jo", ["John"], 90, False),
    ("jde", ["Jude"], 60, False),
    ("rev", ["John"], 90, False),
)


# Each entry: ([(start, end), ...], [authors], date, is_bc) — inclusive ranges.
# Source: https://overviewbible.com/who-wrote-psalms-besides-david/
_PSALMS_RANGES = (
    (
        [
            (3, 9),
            (11, 41),
            (51, 65),
            (68, 70),
            (86, 86),
            (101, 101),
            (103, 103),
            (108, 110),
            (122, 122),
            (124, 124),
            (131, 131),
            (133, 133),
            (138, 145),
        ],
        ["David"],
        1000,
        True,
    ),
    ([(50, 50), (73, 83)], ["Asaph"], 1000, True),
    ([(42, 42), (44, 49), (84, 85), (87, 87)], ["Sons of Korah"], 950, True),
    ([(88, 88)], ["Sons of Korah", "Heman"], 950, True),
    ([(72, 72), (127, 127)], ["Solomon"], 950, True),
    ([(90, 90)], ["Moses"], 1400, True),
    ([(89, 89)], ["Ethan"], 950, True),
)


def _expand_psalm_rows():
    """Yield (book_code, chapter, [authors], date, is_bc) per attributed psalm."""
    for ranges, authors, date, is_bc in _PSALMS_RANGES:
        for start, end in ranges:
            for ch in range(start, end + 1):
                yield ("psa", ch, authors, date, is_bc)


def _seed(apps, schema_editor):
    Author = apps.get_model("bible", "Author")
    Authorship = apps.get_model("bible", "Authorship")

    rows = [(b, None, a, d, bc) for b, a, d, bc in _WHOLE_BOOK_AUTHORSHIPS]
    rows.extend(_expand_psalm_rows())

    unique_names = []
    seen = set()
    for _, _, names, _, _ in rows:
        for n in names:
            if n not in seen:
                seen.add(n)
                unique_names.append(n)

    Author.objects.bulk_create([Author(name=n) for n in unique_names])
    name_to_id = dict(Author.objects.values_list("name", "id"))

    Authorship.objects.bulk_create(
        [
            Authorship(
                book_name=book,
                chapter=chapter,
                author=[name_to_id[n] for n in names],
                date=date,
                is_bc=is_bc,
            )
            for book, chapter, names, date, is_bc in rows
        ]
    )


def _unseed(apps, schema_editor):
    apps.get_model("bible", "Authorship").objects.all().delete()
    apps.get_model("bible", "Author").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0003_concordanceversemapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Authorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=8)),
                ("chapter", models.IntegerField(blank=True, null=True)),
                ("author", models.JSONField(default=list)),
                ("date", models.IntegerField()),
                ("is_bc", models.BooleanField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=["book_name", "chapter"],
                        name="unique_book_chapter_specific",
                        condition=models.Q(chapter__isnull=False),
                    ),
                    models.UniqueConstraint(
                        fields=["book_name"],
                        name="unique_book_chapter_null",
                        condition=models.Q(chapter__isnull=True),
                    ),
                ],
            },
        ),
        migrations.RunPython(_seed, _unseed),
    ]
