# Generated by Django 5.2.14 on 2026-05-22 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0004_author_authorship"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="VerseSpeakerMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=16)),
                ("book", models.CharField(max_length=8)),
                ("chapter", models.IntegerField()),
                ("verse", models.IntegerField()),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verse_mappings",
                        to="bible.speaker",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["version", "book", "chapter", "verse"],
                        name="bible_verse_version_45ba3c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("speaker", "version", "book", "chapter", "verse"),
                        name="unique_speaker_per_verse",
                    )
                ],
            },
        ),
    ]
