# Generated by Django 5.2.14 on 2026-05-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bible", "0008_concordanceversemapping_verse_fk"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="verse",
            new_name="bible_verse_version_3e7e04_idx",
            old_name="bible_verse_vbcv_idx",
        ),
        migrations.RenameIndex(
            model_name="verse",
            new_name="bible_verse_sort_or_5a58d2_idx",
            old_name="bible_verse_sort_idx",
        ),
    ]
